In [2]:
import numpy as np


# Dimension Cero

In [6]:
escalar = np.array(42)
print(escalar)
print(type(escalar))

42
<class 'numpy.ndarray'>


# Vector

In [3]:
vector = np.array([13, 24, 35, 44])
print(vector)

[13 24 35 44]


### Preguntas

#### why in Numpy the shape of an one-dimensional array is (n,) instead of (,n)?

##### Key Points:

- Shape Representation
  - A one-dimensional array in NumPy is essentially a single list of elements, without rows or columns. Its shape is represented as (n,) where n is the number of elements in the array.
  - The comma in (n,) indicates **it's a tuple**, but there's only one dimension. This avoids ambiguity and clearly shows it's not a two-dimensional array.
- No Concept of Rows or Columns in 1D
  - A one-dimensional array doesn't have a second dimension (no rows or columns). Writing the shape as (, n) would incorrectly imply there is an empty first dimension, which isn't true.
- Consistency with Higher Dimensions:
  - In higher-dimensional arrays, the shape tuple includes as many values as there are dimensions. For example:
    - A 2D array has a shape (m, n) (rows and columns).
    - A 3D array has a shape (x, y, z) (depth, rows, columns)

In [19]:
# 1D array
array = np.array([1, 2, 3, 4])
print(array.shape)  # Output: (4,)

# Reshaping into a 2D row vector
row_vector = array.reshape(1, -1)
print(row_vector.shape)  # Output: (1, 4)

# Reshaping into a 2D column vector
column_vector = array.reshape(-1, 1)
print(column_vector.shape)  # Output: (4, 1)

(4,)
(1, 4)
(4, 1)


# Matrices

In [4]:
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(matrix)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


## Preguntas

### Que pasa si uno de los arrays no tiene la misma dimension que los otros?

In [5]:
matrix = np.array([[1, 2, 3], [4, 6], [7, 8, 9]])
print(matrix)

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (3,) + inhomogeneous part.

# Tensor

In [8]:
tensor = np.array([[[1, 2, 3], [4, 5, 6]],
                [[7, 8, 9], [10, 11, 12]]])
print(tensor)
print(tensor.shape) 

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
(2, 2, 3)


# Algunas maneras de crear arrays en Numpy

## Arrange

In [11]:
array_arrange = np.arange(0, 20)
print(array_arrange)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [12]:
array_arrange = np.arange(0, 10, 2)
print(array_arrange)

[0 2 4 6 8]


### Preguntas

#### Que pasa si en un numero de 10 le pongo que emprima de 3 en 3?

In [14]:
array_arrange = np.arange(0, 10, 3)
print(array_arrange)

[0 3 6 9]


In [16]:
array_arrange = np.arange(0, 10, 5)
print(array_arrange)

[0 5]


# Matriz Identidad

In [18]:
eye_matrix = np.eye(4)
print(eye_matrix)
print(eye_matrix.shape)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
(4, 4)


# Matriz diagonal

In [21]:
diag = np.diag([1, 2, 3, 4])
print(diag)

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


# Aleatorio

In [22]:
random = np.random.random((3, 3))
print(random)

[[0.24917861 0.16967127 0.16392358]
 [0.3572736  0.22054069 0.10903719]
 [0.00170758 0.67925046 0.20029345]]


# Atributos

Los arrays son instancias de una clase, por lo que podemos acceder a los atributos y metodos de esta clase

In [24]:
array = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(array)
print(array.ndim)
print(array.shape)
print(array.dtype)

[[1 2 3 4]
 [5 6 7 8]]
2
(2, 4)
int32


## Data Type (dtype)

In [26]:
z = np.array(3, dtype=np.int8)
print(z)

3


In [27]:
double_matrix = np.array([[1, 2, 3], [4, 5, 6]], dtype=np.float64)
print(double_matrix)

[[1. 2. 3.]
 [4. 5. 6.]]


## Astype function

In [28]:
z = z.astype(np.float64)
print(z)

3.0


## Functions

In [29]:
array = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(array)

[[1 2 3 4]
 [5 6 7 8]]


### Sum

In [30]:
sum = np.sum(array)
print(sum)

36


### Mean

In [31]:
mean = np.mean(array)
print(mean)

4.5


### Standard Deviation

In [32]:
std = np.std(array)
print(std)

2.29128784747792


### Transpuesta de una matriz

In [35]:

print("Matriz original: ")
print(matriz)
print("Transpuesta de la matriz:")
print(matriz.T)

Matriz original: 
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Transpuesta de la matriz:
[[1 4 7]
 [2 5 8]
 [3 6 9]]


### Determinante de una matriz

El determinante es un valor único que puede calcularse a partir de una **matriz cuadrada**

In [39]:
matriz = np.array([[1, 12, 3], [4, 5, 6], [7, 8, 9]])
determinante = np.linalg.det(matriz)
print("Determinante de A:")
print(determinante)

Determinante de A:
60.000000000000036


### Inversa de una matriz

In [42]:
matriz = np.array([[1, 12, 3], [4, 5, 6], [7, 8, 9]])
inversa = np.linalg.inv(matriz)
print("Inversa de A:\n")
print(inversa)

Inversa de A:

[[-0.05       -1.4         0.95      ]
 [ 0.1        -0.2         0.1       ]
 [-0.05        1.26666667 -0.71666667]]


# Indexing and Slicing

In [43]:
array = np.array([10,20,30,40,50])
print(array)

[10 20 30 40 50]


## Indexing

In [46]:
print("Primer elemento:",(array[0]))
print("Ultimo elemento:",(array[-1]))
print("Penultimo elemento: ",array[-2])

Primer elemento: 10
Ultimo elemento: 50
Penultimo elemento:  40


## Slicing

In [49]:
array = np.array([10,20,30,40,50])
print(array)

[10 20 30 40 50]


**Nota importante:**

Recordar que **el fin siempre es el fin menos 1**.

Por ejemplo:
- `array(:n)` imprimirá los elementos desde la posicion `0` hasta la posicion `n-1`.

In [47]:
print("Primeros 3 elementos:",array[:3])

Primeros 3 elementos: [10 20 30]


In [48]:
print(array[2:4])

[30 40]


In [54]:
print(array[-1:-4])
raise ValueError("El resultado es un array vacio") # Este error es a proposito 

[]


ValueError: El resultado es un array vacio

### Understanding the Issue with Slicing

The problem with your slicing code is as follows:

```python
print(array[-1:-4])
```
- 1 is the starting index (last element of the array).
- 4 is the ending index (fourth-to-last element, not inclusive).

In Python, **slicing moves from left to right by default**. Since -1 is after -4 in this context, the slice is invalid, resulting in an empty array.

The problem with your slicing code is as follows:

```python
print(array[-1:-4])
```
- 1 is the starting index (last element of the array).
- 4 is the ending index (fourth-to-last element, not inclusive).
In Python, **slicing moves from left to right by default**. Since -1 is after -4 in this context, the slice is invalid, resulting in an empty array.

In [55]:
print(array[-1:-4:-1])  # Output: [50, 40, 30]

[50 40 30]


### Indexacion Booleana

In [57]:
array = np.array([10,20,30,40,50])
print(array)

[10 20 30 40 50]


In [59]:
bool_index = array > 25
print(bool_index)
print(array[bool_index])

[False False  True  True  True]
[30 40 50]


In [60]:
print(array[array <20])

[10]


### Indexacion con arrays de indeces

In [62]:
indexes = [4,0,3]
print(array[indexes])

[50 10 40]


### Indexacion y Slicing para matrices en Numpy

In [64]:
matriz = np.random.randint(0, 10, size=(4, 4))
print(matriz)

[[6 8 3 1]
 [3 6 8 0]
 [4 7 7 3]
 [1 2 5 3]]


In [68]:
# Matriz(row, column) #! indexacion para matrices en Numpy
print(matriz[0, 3])
print(matriz[1, 2])

1
8


In [71]:
# matriz[row_start:row_end, column_start:column_end] #! Slicing para matrices en Numpy
print(matriz[1:3, 1:3])
print(matriz[:2,3:])

[[6 8]
 [7 7]]
[[1]
 [0]]


In [72]:
matriz = np.random.randint(10,100,size=(5,5))
print(matriz)  

[[10 14 83 75 84]
 [50 75 20 13 91]
 [29 98 95 92 81]
 [39 63 54 62 86]
 [24 89 40 96 29]]


In [73]:
print(matriz[2:,2:])

[[95 92 81]
 [54 62 86]
 [40 96 29]]


### Preguntas

#### ¿Qué sucede si excedo el número de elementos al hacer un slice?

In [50]:
print(array[2:22])

[30 40 50]


#### Que pasa si lo hago al contrario de atras para adelante?

In [56]:
print(array[-1:-12:-1])

[50 40 30 20 10]


**El resultado es vacio**