# Broadcasting

In [1]:
import numpy as np

In [2]:
prices = np.array([100, 200, 300, 400, 500])
discount = np.array([0.9])
discount_prices = prices*discount
print(discount_prices)

[ 90. 180. 270. 360. 450.]


In [4]:
prices = np.random.randint(100, 500, size=(3,3))
discount = np.array([0.9,0.5,0.2])
discount_prices = prices*discount
print(prices)
print(discount_prices)

[[446 273 153]
 [451 127 114]
 [480 205 184]]
[[401.4 136.5  30.6]
 [405.9  63.5  22.8]
 [432.  102.5  36.8]]


In [16]:
# Ventas de productos en diferentes tiendas
ventas = np.array([
  [100, 200, 300],
  [400, 500, 600],
  [700, 800, 900]
])

# Bono de ventas por tienda
bono = np.array([
  [10],
  [20],
  [30]
])

ventas_actualizadas = ventas + bono

print("Ventas actualizadas:\n", ventas_actualizadas)

Ventas actualizadas:
 [[110 210 310]
 [420 520 620]
 [730 830 930]]


### Preguntas

#### Que pasa si tengo 2 arrays unidimensionales y pero uno de ellos es mayor al otro?

In [12]:
array1 = np.array([1,2,3])
array2 = np.array([1,2,3,4])
print("Multiplicacion:",array1*array2)
print("Suma:",array1+array2)

ValueError: operands could not be broadcast together with shapes (3,) (4,) 

# Operaciones Logicas

In [8]:
array = np.array([1,2,3,4,5])
print(np.all(array > 0))
print(np.all(array > 9))
print(np.all(array > 2))


True
False
False


In [10]:
print(np.any(array < 1))
print(np.any(array > 4))

False
True


# Concatenacion

In [20]:
arrayA = np.array([1,2,3,4,5])
arrayB = np.array([1,2,3,4,5])
concatenated = np.concatenate((arrayA, arrayB), axis=0) #! axis=0 es para concatenar en vertical
print(concatenated)
print(concatenated.shape)

[1 2 3 4 5 1 2 3 4 5]
(10,)


In [15]:
concatenated = np.concatenate((arrayA, arrayB), axis=1)
print(concatenated)

AxisError: axis 1 is out of bounds for array of dimension 1

# Stacking

In [18]:
arrayA = np.array([1,2,3,4,5])
arrayB = np.array([1,2,3,4,5])

stacked_v =np.vstack((arrayA, arrayB))
print(stacked_v)

[[1 2 3 4 5]
 [1 2 3 4 5]]


In [19]:
arrayA = np.array([1,2,3,4,5])
arrayB = np.array([1,2,3,5])

stacked_v =np.vstack((arrayA, arrayB))
print(stacked_v)

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 5 and the array at index 1 has size 4

In [21]:
arrayA = np.array([1,2,3,4,5])
arrayB = np.array([1,2,3,5])

stacked_h =np.hstack((arrayA, arrayB))
print(stacked_h)

[1 2 3 4 5 1 2 3 5]


# Split

In [25]:
array= np.arange(1,10)
splited_array = np.split(array, 3) # ! Me devuelve una lista!!
print(array)
print(splited_array)
print(type(splited_array))

[1 2 3 4 5 6 7 8 9]
[array([1, 2, 3]), array([4, 5, 6]), array([7, 8, 9])]
<class 'list'>


In [23]:
array= np.arange(1,9)
print(array)
print(np.split(array, 3))

[1 2 3 4 5 6 7 8]


ValueError: array split does not result in an equal division