In [1]:
import numpy as np

# Unique

In [3]:
survey_responses = np.array(["bueno", "excelente", "malo", "bueno", "bueno", "malo", "malo", "bueno", "excelente", "malo","excelente", "bueno", "bueno", "malo", "excelente"])
print(np.unique(survey_responses))
print(np.unique(survey_responses, return_counts=True))

['bueno' 'excelente' 'malo']
(array(['bueno', 'excelente', 'malo'], dtype='<U9'), array([6, 4, 5], dtype=int64))


In [4]:
unique_values, counts = np.unique(survey_responses, return_counts=True)
print("Unique Values:", unique_values)
print("Counts:", counts)

Unique Values: ['bueno' 'excelente' 'malo']
Counts: [6 4 5]


# Copias y vistas

El problema es que el slicing devuelve referencias

In [10]:
array_x = np.arange(10)
view_x = array_x[1:3]
print(array_x)
print(view_x)

[0 1 2 3 4 5 6 7 8 9]
[1 2]


In [11]:
array_x[1:3] = [10,11]
print(array_x)
print(view_x)

[ 0 10 11  3  4  5  6  7  8  9]
[10 11]


In [12]:
view_x[:] = [20,21]
print(array_x)
print(view_x)

[ 0 20 21  3  4  5  6  7  8  9]
[20 21]


## Copias

### Fancy Indexing

In [13]:
array_x = np.arange(10)
copy_x = array_x[[1,2]]
print(array_x)
print(copy_x)

[0 1 2 3 4 5 6 7 8 9]
[1 2]


In [14]:
array_x[1:3] = [10,11]
print(array_x)
print(copy_x)  

[ 0 10 11  3  4  5  6  7  8  9]
[1 2]


In [22]:
array_x = np.arange(20,50)
copy_x = array_x[[5,8,12]]
print(array_x)
print(copy_x)


[20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43
 44 45 46 47 48 49]
[25 28 32]


**Nota importante:**

- **Solo se pueden realizar indexaciones.**
- No se puede usar slicing directamente, ya que este genera una **vista** (referencia a la matriz original).

Si necesitas evitar que el slicing genere una vista y deseas crear una copia independiente, utiliza el método `.copy()` al final.

#### Ejemplo:
```python
copy_x = array_x[1:3].copy()