In [2]:
import numpy as np

# Transformacion de arrays

## Transpuesta de una matriz

In [3]:
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
transposed_matrix_1 = np.transpose(matrix)
transposed_matrix_2 = matrix.T
print(matrix)
print(transposed_matrix_1)
print(transposed_matrix_2)


[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 4 7]
 [2 5 8]
 [3 6 9]]
[[1 4 7]
 [2 5 8]
 [3 6 9]]


## Reshape

In [7]:
array = np.arange(1,13)
reshaped_array = array.reshape(3,4)
print(array)
print(reshaped_array)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


#### Uso del -1

In [8]:
arr = np.array([1, 2, 3, 4, 5, 6])
reshaped = arr.reshape((-1, 2))  # Cambia automáticamente el número de filas
print(reshaped)


[[1 2]
 [3 4]
 [5 6]]


#### Matriz a vector

In [9]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
reshaped = arr.reshape(-1)
print(arr)
print(reshaped)

[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]


# Reverse

In [15]:
array = np.arange(1,13)
reversed_1 = array[-1:-13:-1]
reversed_2 = array[::-1]


print(array)
print(reversed_1)
print(reversed_2)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[12 11 10  9  8  7  6  5  4  3  2  1]
[12 11 10  9  8  7  6  5  4  3  2  1]


# Flattening

In [16]:
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
flattened = matrix.flatten()
print(matrix)
print(flattened)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 2 3 4 5 6 7 8 9]


In [17]:
cube = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
flattened = cube.flatten()
print(cube)
print(flattened)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
[ 1  2  3  4  5  6  7  8  9 10 11 12]
