In [2]:
import numpy as np

# Producto

In [4]:
matrix_a = np.array([[1, 2], [3, 4]])
matrix_b = np.array([[5, 6], [7, 8]])
product_1 = np.dot(matrix_a, matrix_b)
product_2 = matrix_a @ matrix_b
product_3 = matrix_a*matrix_b #! Esta no es una multiplicación de matrices, es una multiplicación elemento a elemento

print(product_1)
print(product_2)
print(product_3)

[[19 22]
 [43 50]]
[[19 22]
 [43 50]]
[[ 5 12]
 [21 32]]


# Resolver un sistema de ecuaciones 2x2 con NumPy

**Sistema de ecuaciones:**

1. \( 2x + 3y = 8 \)  
2. \( x - y = 2 \)

[ 2  3 ]   [ x ]   =   [ 8 ]

[ 1 -1 ] ⋅ [ y ]   =   [ 2 ]

Donde:

A (matriz de coeficientes):

[ 2  3 ]

[ 1 -1 ]

b (vector de términos independientes):

[ 8 ]

[ 2 ]

x (vector solución):

[ x ]

[ y ]

In [6]:
import numpy as np

# Matriz de coeficientes (A)
A = np.array([[2, 3],
            [1, -1]])

# Vector de términos independientes (b)
b = np.array([8, 2])

# Resolver el sistema de ecuaciones
solution = np.linalg.solve(A, b)

# Mostrar resultados
print("La solución es:")
print(f"x = {solution[0]}")
print(f"y = {solution[1]}")

La solución es:
x = 2.8
y = 0.8
