In [3]:
import pandas as pd
import numpy as np

# Como crear dfs en Pandas

In [14]:
path = r'C:\Users\seboc\OneDrive\Escritorio\PROJECTS\DATASCIENCE\CursoPythonDataScience\Online_Retail.csv'
retail_data = pd.read_csv(path,encoding='windows-1252')
print(type(retail_data))
print(retail_data.head())

#Excel
#data_excel = pd.read_excel(path)

#Json
#data_json = pd.read_json(path)

<class 'pandas.core.frame.DataFrame'>
  InvoiceNo StockCode                          Description  Quantity  \
0    536365    85123A   WHITE HANGING HEART T-LIGHT HOLDER         6   
1    536365     71053                  WHITE METAL LANTERN         6   
2    536365    84406B       CREAM CUPID HEARTS COAT HANGER         8   
3    536365    84029G  KNITTED UNION FLAG HOT WATER BOTTLE         6   
4    536365    84029E       RED WOOLLY HOTTIE WHITE HEART.         6   

    InvoiceDate  UnitPrice  CustomerID         Country  
0  12/1/10 8:26       2.55     17850.0  United Kingdom  
1  12/1/10 8:26       3.39     17850.0  United Kingdom  
2  12/1/10 8:26       2.75     17850.0  United Kingdom  
3  12/1/10 8:26       3.39     17850.0  United Kingdom  
4  12/1/10 8:26       3.39     17850.0  United Kingdom  


## Creando df a partir de arrays de NumPy

In [16]:
data = np.array([[1,2,3],[4,5,6],[7,8,9]])

df_from_array = pd.DataFrame(data, columns=['A','B','C'])

print(data)
print(df_from_array)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
   A  B  C
0  1  2  3
1  4  5  6
2  7  8  9


## Creando df a partir de Litas y diccionarios nativos de python

In [17]:
data = [[1,'Sebastian',24],[2,'Juan',25],[3,'Pedro',26]]

df_from_list = pd.DataFrame(data, columns=['ID','Name','Age'])

print(data)
print(df_from_list)

[[1, 'Sebastian', 24], [2, 'Juan', 25], [3, 'Pedro', 26]]
   ID       Name  Age
0   1  Sebastian   24
1   2       Juan   25
2   3      Pedro   26


In [20]:
data = [{'ID':1,'Name':'Sebastian','Age':24},    
        {'ID':2,'Name':'Juan','Age':25},
        {'ID':3,'Name':'Pedro','Age':26}]

df_from_dictionary = pd.DataFrame(data)

print(data)
print(df_from_dictionary)

[{'ID': 1, 'Name': 'Sebastian', 'Age': 24}, {'ID': 2, 'Name': 'Juan', 'Age': 25}, {'ID': 3, 'Name': 'Pedro', 'Age': 26}]
   ID       Name  Age
0   1  Sebastian   24
1   2       Juan   25
2   3      Pedro   26


In [21]:
data = {'ID':[1,2,3],'Name':['Sebastian','Juan','Pedro'],'Age':[24,25,26]}
df_from_dictionary = pd.DataFrame(data)

print(data)
print(df_from_dictionary)

{'ID': [1, 2, 3], 'Name': ['Sebastian', 'Juan', 'Pedro'], 'Age': [24, 25, 26]}
   ID       Name  Age
0   1  Sebastian   24
1   2       Juan   25
2   3      Pedro   26


## Creando df a partir de series

In [26]:
data = {'ID':pd.Series([1,2,3],index=['a','b','c']),    
        'Name':pd.Series(['Sebastian','Juan','Pedro'],index=['a','b','c']),
        'Age':pd.Series([24,25,26],index=['a','b','c'])}

df_from_dictionary_with_series = pd.DataFrame(data)

print(data)
print(df_from_dictionary_with_series)

{'ID': a    1
b    2
c    3
dtype: int64, 'Name': a    Sebastian
b         Juan
c        Pedro
dtype: object, 'Age': a    24
b    25
c    26
dtype: int64}
   ID       Name  Age
a   1  Sebastian   24
b   2       Juan   25
c   3      Pedro   26
